import java.util.Properties
import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.jetbrainsCompose)
    alias(libs.plugins.compose.compiler)
    kotlin("plugin.serialization") version libs.versions.kotlin.get()
}

// ── App config ───────────────────────────────────────────────────────────────
// All runtime config lives in local.properties (gitignored).
// Add entries there; they are injected into Android via BuildConfig and into
// iOS via a generated Kotlin source file at build time.
val localProps = Properties().also { props: Properties ->
    val f = rootProject.file("local.properties")
    if (f.exists()) props.load(f.inputStream())
}
val apiHostValue: String  = localProps.getProperty("API_HOST",  "localhost")
val authPortValue: String = localProps.getProperty("AUTH_PORT", "8080")
val apiPortValue: String  = localProps.getProperty("API_PORT",  "8081")

// Generates AppConfig.kt directly into the iosMain source tree so the IDE
// can resolve the constants without a prior Gradle build.  The file is
// gitignored (it contains machine-specific values from local.properties).
val generateIosAppConfig by tasks.registering {
    // Write straight into the checked-in source directory so IntelliJ / AS
    // indexes it as a regular source file — no kotlin.srcDir plumbing needed.
    val outputFile = file(
        "src/iosMain/kotlin/com/vdigital/volumestream/config/AppConfig.kt"
    )
    // Declare local.properties as an input so the task is re-run whenever
    // the host/port values change (busts Gradle's up-to-date check).
    inputs.file(rootProject.file("local.properties"))
    outputs.file(outputFile)
    doFirst {
        outputFile.parentFile.mkdirs()
        outputFile.writeText(
            "// AUTO-GENERATED by composeApp/build.gradle.kts — do not edit by hand.\n" +
            "// Re-generated on every build from local.properties values.\n" +
            "package com.vdigital.volumestream.config\n\n" +
            "internal val API_HOST:   String = \"$apiHostValue\"\n" +
            "internal val AUTH_PORT:  Int    = $authPortValue\n" +
            "internal val API_PORT:   Int    = $apiPortValue\n"
        )
    }
}
// ─────────────────────────────────────────────────────────────────────────────

kotlin {
    applyDefaultHierarchyTemplate()
    androidTarget {
        @OptIn(ExperimentalKotlinGradlePluginApi::class)
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }
    }

    listOf(
        iosX64(),
        iosArm64(),
        iosSimulatorArm64(),
        tvosX64(),
        tvosArm64(),
        tvosSimulatorArm64(),
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
            export(project(":core:player"))
        }
    }

    sourceSets {
        androidMain.dependencies {
            implementation(compose.preview)
            implementation(libs.androidx.activity.compose)
            implementation(libs.koin.android)
            implementation(libs.android.splashscreen)
            implementation(libs.androidx.media3.exoplayer.dash)
            implementation(libs.androidx.tv.material)
        }
        commonMain.dependencies {
            implementation(project(":data"))
            implementation(project(":core:navigation"))
            api(project(":core:player"))
            implementation(project(":feature:home"))
            implementation(project(":feature:playback"))
            implementation(project(":feature:profile"))
            implementation(project(":feature:settings"))
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material)
            implementation(compose.ui)
            implementation(compose.components.resources)
            implementation(compose.components.uiToolingPreview)
            implementation(libs.napier)
            implementation(libs.androidx.lifecycle.runtime.compose)
            implementation(libs.lifecycle.viewmodel.compose)
            implementation(libs.koin.compose)
            implementation(libs.koin.composeVM)
            implementation(libs.koin.core)
            implementation(libs.navigation.compose)
            implementation(libs.image.loader)
        }
        iosMain {
            dependencies {
                implementation(libs.koin.core)
            }
        }
        // tvOS — dedicated source set (different ViewController, same Koin setup)
        // KMP hierarchy template creates tvosMain automatically; use `by getting`.
        val tvosMain by getting {
            dependencies { implementation(libs.koin.core) }
        }
    }
}

android {
    namespace = "com.vdigital.volumestream"
    compileSdk = libs.versions.android.compileSdk.get().toInt()

    sourceSets["main"].manifest.srcFile("src/androidMain/AndroidManifest.xml")
    sourceSets["main"].res.srcDirs("src/androidMain/res")
    sourceSets["main"].resources.srcDirs("src/commonMain/resources")

    defaultConfig {
        applicationId = "com.vdigital.volumestream"
        minSdk = libs.versions.android.minSdk.get().toInt()
        targetSdk = libs.versions.android.targetSdk.get().toInt()
        versionCode = 1
        versionName = "1.0"
        buildConfigField("String", "API_HOST",  "\"$apiHostValue\"")
        buildConfigField("int",    "AUTH_PORT", authPortValue)
        buildConfigField("int",    "API_PORT",  apiPortValue)
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
    buildFeatures {
        compose = true
        buildConfig = true
    }
    flavorDimensions += "device"
    productFlavors {
        create("phone") {
            dimension = "device"
            applicationIdSuffix = ".phone"
            versionNameSuffix = "-phone"
        }
        create("tv") {
            dimension = "device"
            applicationIdSuffix = ".tv"
            versionNameSuffix = "-tv"
        }
    }
    dependencies {
        debugImplementation(compose.uiTooling)
    }
}
dependencies {
    implementation(libs.androidx.lifecycle.common.jvm)
}

// Keep AppConfig.kt up to date whenever any iOS Kotlin target is compiled.
tasks.matching { it.name.startsWith("compileKotlinIos") }.configureEach {
    dependsOn(generateIosAppConfig)
}

// Same for tvOS — generate AppConfig into the tvosMain source tree.
val generateTvosAppConfig by tasks.registering {
    val outputFile = file("src/tvosMain/kotlin/com/vdigital/volumestream/config/AppConfig.kt")
    inputs.file(rootProject.file("local.properties"))
    outputs.file(outputFile)
    doFirst {
        outputFile.parentFile.mkdirs()
        outputFile.writeText(
            "// AUTO-GENERATED by composeApp/build.gradle.kts — do not edit by hand.\n" +
            "// Re-generated on every build from local.properties values.\n" +
            "package com.vdigital.volumestream.config\n\n" +
            "internal val API_HOST:   String = \"$apiHostValue\"\n" +
            "internal val AUTH_PORT:  Int    = $authPortValue\n" +
            "internal val API_PORT:   Int    = $apiPortValue\n"
        )
    }
}
tasks.matching { it.name.startsWith("compileKotlinTvos") }.configureEach {
    dependsOn(generateTvosAppConfig)
}
