import java.util.Properties
import java.net.NetworkInterface
import java.util.Collections
import java.io.ByteArrayOutputStream
import org.jetbrains.kotlin.gradle.ExperimentalKotlinGradlePluginApi
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.jetbrainsCompose)
    alias(libs.plugins.compose.compiler)
    kotlin("plugin.serialization") version libs.versions.kotlin.get()
}

// ── App config ───────────────────────────────────────────────────────────────
// All runtime config lives in local.properties (gitignored).
// Add entries there; they are injected into Android via BuildConfig and into
// iOS via a generated Kotlin source file at build time.
val localProps = Properties().also { props: Properties ->
    val f = rootProject.file("local.properties")
    if (f.exists()) props.load(f.inputStream())
}
val apiHostValue: String  = localProps.getProperty("API_HOST",  "localhost")
val authPortValue: String = localProps.getProperty("AUTH_PORT", "8080")
val apiPortValue: String  = localProps.getProperty("API_PORT",  "8081")

val updateApiHostFromNetwork by tasks.registering {
    group = "configuration"
    description = "Detects this machine's LAN IPv4 and writes it to local.properties as API_HOST"
    doLast {
        val interfaces = Collections.list(NetworkInterface.getNetworkInterfaces())
            .filter { it.isUp && !it.isLoopback && !it.isVirtual }
            .filterNot {
                it.name.startsWith("docker") ||
                it.name.startsWith("vbox") ||
                it.name.startsWith("bridge") ||
                it.name.startsWith("utun")
            }
            .sortedBy {
                when {
                    it.name.startsWith("en") -> 0
                    it.name.startsWith("wlan") -> 1
                    it.name.startsWith("eth") -> 2
                    else -> 3
                }
            }

        val lanIp = interfaces.firstNotNullOfOrNull { networkInterface ->
            Collections.list(networkInterface.inetAddresses)
                .mapNotNull { address ->
                    val host = address.hostAddress ?: return@mapNotNull null
                    if (
                        host.contains(":") ||
                        host == "127.0.0.1" ||
                        host.startsWith("169.254.")
                    ) null else host
                }
                .firstOrNull()
        } ?: throw org.gradle.api.GradleException(
            "Could not detect a LAN IPv4 address. Connect to Wi-Fi/Ethernet and try again."
        )

        val localPropertiesFile = rootProject.file("local.properties")
        if (!localPropertiesFile.exists()) {
            localPropertiesFile.createNewFile()
        }

        val props = Properties()
        if (localPropertiesFile.length() > 0L) {
            localPropertiesFile.inputStream().use { props.load(it) }
        }
        props.setProperty("API_HOST", lanIp)
        localPropertiesFile.outputStream().use {
            props.store(it, "Updated by :composeApp:updateApiHostFromNetwork")
        }

        logger.lifecycle("API_HOST set to $lanIp in ${localPropertiesFile.absolutePath}")
    }
}

// Generates AppConfig.kt directly into the iosMain source tree so the IDE
// can resolve the constants without a prior Gradle build.  The file is
// gitignored (it contains machine-specific values from local.properties).
val generateIosAppConfig by tasks.registering {
    // Write straight into the checked-in source directory so IntelliJ / AS
    // indexes it as a regular source file — no kotlin.srcDir plumbing needed.
    val outputFile = file(
        "src/iosMain/kotlin/com/vdigital/volumestream/config/AppConfig.kt"
    )
    // Declare local.properties as an input so the task is re-run whenever
    // the host/port values change (busts Gradle's up-to-date check).
    inputs.file(rootProject.file("local.properties"))
    outputs.file(outputFile)
    doFirst {
        outputFile.parentFile.mkdirs()
        outputFile.writeText(
            "// AUTO-GENERATED by composeApp/build.gradle.kts — do not edit by hand.\n" +
            "// Re-generated on every build from local.properties values.\n" +
            "package com.vdigital.volumestream.config\n\n" +
            "internal val API_HOST:   String = \"$apiHostValue\"\n" +
            "internal val AUTH_PORT:  Int    = $authPortValue\n" +
            "internal val API_PORT:   Int    = $apiPortValue\n"
        )
    }
}
// ─────────────────────────────────────────────────────────────────────────────

kotlin {
    applyDefaultHierarchyTemplate()
    androidTarget {
        @OptIn(ExperimentalKotlinGradlePluginApi::class)
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }
    }

    listOf(
        iosX64(),
        iosArm64(),
        iosSimulatorArm64(),
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
            export(project(":core:player"))
        }
    }

    sourceSets {
        androidMain.dependencies {
            implementation(compose.preview)
            implementation(libs.androidx.activity.compose)
            implementation(libs.koin.android)
            implementation(libs.android.splashscreen)
            implementation(libs.androidx.media3.exoplayer.dash)
            implementation(libs.androidx.tv.material)
        }
        commonMain.dependencies {
            implementation(project(":data"))
            implementation(project(":core:navigation"))
            api(project(":core:player"))
            implementation(project(":feature:home"))
            implementation(project(":feature:playback"))
            implementation(project(":feature:profile"))
            implementation(project(":feature:settings"))
            implementation(compose.runtime)
            implementation(compose.foundation)
            implementation(compose.material)
            implementation(compose.ui)
            implementation(compose.components.resources)
            implementation(compose.components.uiToolingPreview)
            implementation(libs.napier)
            implementation(libs.androidx.lifecycle.runtime.compose)
            implementation(libs.lifecycle.viewmodel.compose)
            implementation(libs.koin.compose)
            implementation(libs.koin.composeVM)
            implementation(libs.koin.core)
            implementation(libs.navigation.compose)
            implementation(libs.image.loader)
        }
        iosMain {
            dependencies {
                implementation(libs.koin.core)
            }
        }
    }
}

android {
    namespace = "com.vdigital.volumestream"
    compileSdk = libs.versions.android.compileSdk.get().toInt()

    sourceSets["main"].manifest.srcFile("src/androidMain/AndroidManifest.xml")
    sourceSets["main"].res.srcDirs("src/androidMain/res")
    sourceSets["main"].resources.srcDirs("src/commonMain/resources")

    defaultConfig {
        applicationId = "com.vdigital.volumestream"
        minSdk = libs.versions.android.minSdk.get().toInt()
        targetSdk = libs.versions.android.targetSdk.get().toInt()
        versionCode = 1
        versionName = "1.0"
        buildConfigField("String", "API_HOST",  "\"$apiHostValue\"")
        buildConfigField("int",    "AUTH_PORT", authPortValue)
        buildConfigField("int",    "API_PORT",  apiPortValue)
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
    buildFeatures {
        compose = true
        buildConfig = true
    }
    flavorDimensions += "device"
    productFlavors {
        create("phone") {
            dimension = "device"
            applicationIdSuffix = ".phone"
            versionNameSuffix = "-phone"
        }
        create("tv") {
            dimension = "device"
            applicationIdSuffix = ".tv"
            versionNameSuffix = "-tv"
        }
    }
    dependencies {
        debugImplementation(compose.uiTooling)
    }
}
dependencies {
    implementation(libs.androidx.lifecycle.common.jvm)
}

tasks.named("preBuild") {
    dependsOn(updateApiHostFromNetwork)
}

// Keep AppConfig.kt up to date whenever iOS Kotlin sources are compiled.
tasks.matching {
    it.name.startsWith("compileKotlinIos") ||
    it.name == "compileIosMainKotlinMetadata"
}.configureEach {
    dependsOn(generateIosAppConfig)
}

fun projectEnvOrDefault(name: String, defaultValue: String): String =
    System.getenv(name)?.takeIf { it.isNotBlank() } ?: defaultValue

fun adbExecutableName(): String = if (System.getProperty("os.name").lowercase().contains("win")) "adb.exe" else "adb"

fun resolveAdbExecutable(): String {
    val adbOverride = System.getenv("ADB")?.trim().orEmpty()
    if (adbOverride.isNotEmpty()) return adbOverride

    val adbName = adbExecutableName()
    val candidates = mutableListOf<String>()

    fun addSdkCandidate(sdkRoot: String?) {
        val root = sdkRoot?.trim().orEmpty()
        if (root.isEmpty()) return
        candidates += "$root/platform-tools/$adbName"
    }

    addSdkCandidate(System.getenv("ANDROID_SDK_ROOT"))
    addSdkCandidate(System.getenv("ANDROID_HOME"))
    addSdkCandidate(localProps.getProperty("sdk.dir"))

    val found = candidates.firstOrNull { file(it).exists() }
    if (found != null) return found

    // Fall back to PATH-based resolution for environments where adb is globally available.
    return adbName
}

fun adbTargetArgs(): List<String> {
    val serial = System.getenv("ANDROID_SERIAL")?.trim().orEmpty()
    return if (serial.isNotEmpty()) listOf("-s", serial) else emptyList()
}

data class AdbDevice(val serial: String, val state: String) {
    val isEmulator: Boolean get() = serial.startsWith("emulator-")
}

fun listAdbDevices(adb: String): List<AdbDevice> {
    val out = ByteArrayOutputStream()
    exec {
        commandLine(adb, "devices")
        standardOutput = out
    }
    val devicesText = out.toString().trim()
    return devicesText
        .lineSequence()
        .drop(1)
        .map { it.trim() }
        .filter { it.isNotEmpty() && it.contains("\t") }
        .map { line ->
            val parts = line.split(Regex("\\s+"))
            AdbDevice(serial = parts[0], state = parts.getOrElse(1) { "unknown" })
        }
        .toList()
}

fun resolveAdbTargetArgs(adb: String, preferEmulator: Boolean): List<String> {
    val configuredSerial = System.getenv("ANDROID_SERIAL")?.trim().orEmpty()
    val devices = listAdbDevices(adb)
    val onlineDevices = devices.filter { it.state == "device" }

    if (configuredSerial.isNotEmpty()) {
        val matched = devices.firstOrNull { it.serial == configuredSerial }
        if (matched == null) {
            val known = devices.joinToString { "${it.serial}(${it.state})" }
            throw GradleException("ANDROID_SERIAL '$configuredSerial' not found in adb devices. Known: ${if (known.isBlank()) "none" else known}")
        }
        if (matched.state != "device") {
            throw GradleException("ANDROID_SERIAL '$configuredSerial' is '${matched.state}'. Ensure it is online/authorized, then re-run.")
        }
        return listOf("-s", configuredSerial)
    }

    if (onlineDevices.isEmpty()) {
        throw GradleException(
            "No Android device/emulator found for adb. Start a device in Android Studio Device Manager (or connect a physical device) and re-run."
        )
    }

    if (onlineDevices.size == 1) {
        return listOf("-s", onlineDevices.first().serial)
    }

    if (preferEmulator) {
        val emulators = onlineDevices.filter { it.isEmulator }
        if (emulators.size == 1) {
            return listOf("-s", emulators.first().serial)
        }
    }

    val choices = onlineDevices.joinToString { it.serial }
    throw GradleException("Multiple adb targets are online: $choices. Set ANDROID_SERIAL to choose one.")
}

tasks.register("launchPhoneDebugFromIde") {
    group = "ide"
    description = "Assemble, install, and launch the Android phone debug app (uses ANDROID_SERIAL when set)."
    dependsOn("assemblePhoneDebug")
    doLast {
        val adb = resolveAdbExecutable()
        val targetArgs = resolveAdbTargetArgs(adb, preferEmulator = false)
        val apk = layout.buildDirectory.file("outputs/apk/phone/debug/composeApp-phone-debug.apk").get().asFile
        if (!apk.exists()) {
            throw GradleException("Phone APK not found: ${apk.absolutePath}")
        }
        exec {
            commandLine(listOf(adb) + targetArgs + listOf("install", "-r", apk.absolutePath))
        }
        exec {
            commandLine(
                listOf(adb) + targetArgs + listOf(
                    "shell", "am", "start", "-W", "-n",
                    "com.vdigital.volumestream.phone/com.vdigital.volumestream.platform.activity.MainActivity"
                )
            )
        }
    }
}

tasks.register("launchTvDebugFromIde") {
    group = "ide"
    description = "Assemble, install, and launch the Android TV debug app (uses ANDROID_SERIAL when set)."
    dependsOn("assembleTvDebug")
    doLast {
        val adb = resolveAdbExecutable()
        val targetArgs = resolveAdbTargetArgs(adb, preferEmulator = true)
        val apk = layout.buildDirectory.file("outputs/apk/tv/debug/composeApp-tv-debug.apk").get().asFile
        if (!apk.exists()) {
            throw GradleException("TV APK not found: ${apk.absolutePath}")
        }
        exec {
            commandLine(listOf(adb) + targetArgs + listOf("install", "-r", apk.absolutePath))
        }
        exec {
            commandLine(
                listOf(adb) + targetArgs + listOf(
                    "shell", "am", "start", "-W", "-n",
                    "com.vdigital.volumestream.tv/com.vdigital.volumestream.platform.activity.TvMainActivity"
                )
            )
        }
    }
}

tasks.register("launchIosSimulatorFromIde") {
    group = "ide"
    description = "Build, install, and launch iosApp on the selected iOS simulator."
    doLast {
        val simulatorName = projectEnvOrDefault("IOS_SIMULATOR", "iPhone 16e")
        val scheme = projectEnvOrDefault("IOS_SCHEME", "iosApp")
        val bundleId = projectEnvOrDefault("IOS_BUNDLE_ID", "com.vdigital.volumestream.VolumeStream")
        val projectPath = rootProject.file("iosApp/iosApp.xcodeproj").absolutePath
        val derivedDataPath = rootProject.file("build/ios_derived/ide").absolutePath
        val appPath = "$derivedDataPath/Build/Products/Debug-iphonesimulator/$scheme.app"

        val shellCommand = """
            set -euo pipefail
            SIMCTL_JSON="${'$'}(xcrun simctl list devices available -j)"
            SIMULATOR_UDID="${'$'}(SIMCTL_JSON="${'$'}SIMCTL_JSON" /usr/bin/python3 - "${'$'}SIMULATOR" <<'PY'
import json
import os
import sys

requested = (sys.argv[1] if len(sys.argv) > 1 else "").strip()
data = json.loads(os.environ["SIMCTL_JSON"])

ios_devices = []
for runtime, devices in data.get("devices", {}).items():
    if "iOS" not in runtime:
        continue
    for d in devices:
        if d.get("isAvailable"):
            ios_devices.append(d)

def pick_requested():
    if not requested:
        return None
    req_lower = requested.lower()
    for d in ios_devices:
        if d.get("udid", "").lower() == req_lower:
            return d
    for d in ios_devices:
        if d.get("name", "").lower() == req_lower:
            return d
    return None

picked = pick_requested()
if picked is None:
    booted = [d for d in ios_devices if d.get("state") == "Booted"]
    if booted:
        picked = booted[0]
if picked is None and ios_devices:
    picked = ios_devices[0]

if picked is None:
    sys.stderr.write("No available iOS simulators found.\n")
    sys.exit(2)

print(picked["udid"])
PY
            )"

            if [[ -z "${'$'}SIMULATOR_UDID" ]]; then
                echo "Failed to resolve an iOS simulator UDID." >&2
                exit 2
            fi

            echo "Using iOS simulator: ${'$'}SIMULATOR (UDID=${'$'}SIMULATOR_UDID)"
            xcrun simctl boot "${'$'}SIMULATOR_UDID" >/dev/null 2>&1 || true
            xcrun simctl bootstatus "${'$'}SIMULATOR_UDID" -b

            xcodebuild -project "${'$'}PROJECT_PATH" -scheme "${'$'}SCHEME" -configuration Debug -destination "platform=iOS Simulator,id=${'$'}SIMULATOR_UDID" -derivedDataPath "${'$'}DERIVED_DATA" build

            EFFECTIVE_APP_PATH="${'$'}APP_PATH"
            if [[ ! -d "${'$'}EFFECTIVE_APP_PATH" ]]; then
                EFFECTIVE_APP_PATH="${'$'}(find "${'$'}DERIVED_DATA/Build/Products/Debug-iphonesimulator" -maxdepth 1 -type d -name '*.app' | head -n 1)"
            fi
            if [[ -z "${'$'}EFFECTIVE_APP_PATH" || ! -d "${'$'}EFFECTIVE_APP_PATH" ]]; then
                echo "Built .app was not found under ${'$'}DERIVED_DATA/Build/Products/Debug-iphonesimulator" >&2
                exit 3
            fi

            xcrun simctl install "${'$'}SIMULATOR_UDID" "${'$'}EFFECTIVE_APP_PATH"

            EFFECTIVE_BUNDLE_ID="${'$'}(/usr/libexec/PlistBuddy -c 'Print:CFBundleIdentifier' "${'$'}EFFECTIVE_APP_PATH/Info.plist" 2>/dev/null || true)"
            if [[ -z "${'$'}EFFECTIVE_BUNDLE_ID" ]]; then
                EFFECTIVE_BUNDLE_ID="${'$'}BUNDLE_ID"
            fi
            xcrun simctl launch "${'$'}SIMULATOR_UDID" "${'$'}EFFECTIVE_BUNDLE_ID"
        """.trimIndent()

        exec {
            environment(
                mapOf(
                    "SIMULATOR" to simulatorName,
                    "SCHEME" to scheme,
                    "BUNDLE_ID" to bundleId,
                    "PROJECT_PATH" to projectPath,
                    "DERIVED_DATA" to derivedDataPath,
                    "APP_PATH" to appPath,
                )
            )
            commandLine("/bin/zsh", "-lc", shellCommand)
        }
    }
}

