// AUTO-GENERATED by composeApp/build.gradle.kts — do not edit by hand.
// Re-generated on every build from local.properties values.
package com.vdigital.volumestream.config

internal val API_HOST:   String = "localhost"
internal val AUTH_PORT:  Int    = 18443
internal val API_PORT:   Int    = 8081
internal val AUTH_USE_HTTPS: Boolean = true
internal val API_USE_HTTPS:  Boolean = true
internal val USE_HTTPS:      Boolean = true
